---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes-app
  template:
    metadata:
      labels:
        app: heroes-app
    spec:
      containers:
      - name: heroes-app
        image: jasondippel/node-heroes-app:latest
        env:
          - name: VILLAINS_SERVICE
            value: "http://villains-service:3001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: heroes-service
spec:
  type: NodePort
  selector:
    app: heroes-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
