---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villains-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: villains-app
  template:
    metadata:
      labels:
        app: villains-app
    spec:
      containers:
      - name: villains-app
        image: jasondippel/node-villains-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: villains-service
spec:
  selector:
    app: villains-app
  ports:
  - port: 3001
    targetPort: 3001
